btw_app_homepage:
    pattern:  /
    defaults: { _controller: BtwAppBundle:Analysis:index }

btw_app_detail:
    pattern : /detail/{year}
    defaults: { _controller: BtwAppBundle:Detail:index }

btw_app_ajax_states:
      pattern : /detail/{year}/states
      defaults: { _controller: BtwAppBundle:Detail:listStates }
      options:
          expose: true

btw_app_ajax_constituencies:
      pattern : /detail/states/{stateId}/constituencies
      defaults: { _controller: BtwAppBundle:Detail:listConstituencies }
      options:
          expose: true

btw_app_ajax_year_results:
      pattern : /detail/results/{year}
      defaults: { _controller: BtwAppBundle:Detail:electionResults }
      options:
          expose : true

btw_app_closest:
      pattern : /detail/closest/{partyId}
      defaults: { _controller: BtwAppBundle:Detail:closest }
      options:
          expose : true

###### Voting ######
btw_app_vote:
    pattern: /vote
    defaults: { _controller: BtwAppBundle:Voter:index }

btw_app_vote_ballot:
    pattern: /vote/ballot
    defaults: { _controller: BtwAppBundle:Voter:ballot }

btw_app_vote_submit:
    pattern: /vote/submit
    defaults: { _controller: BtwAppBundle:Voter:submit }

btw_app_vote_create:
    pattern: /vote/create
    defaults: { _controller: BtwAppBundle:Voter:createVoter }

###### Benchmark ######
btw_benchmark_q1:
    pattern: /benchmark/q1/{year}
    defaults: { _controller: BtwAppBundle:Benchmark:q1 }

btw_benchmark_q2:
    pattern: /benchmark/q2/{year}
    defaults: { _controller: BtwAppBundle:Benchmark:q2 }

btw_benchmark_q3:
    pattern: /benchmark/q3/{constituencyId}
    defaults: { _controller: BtwAppBundle:Benchmark:q3 }

btw_benchmark_q4:
    pattern: /benchmark/q4/{year}
    defaults: { _controller: BtwAppBundle:Benchmark:q4 }

btw_benchmark_q5:
    pattern: /benchmark/q5/{year}
    defaults: { _controller: BtwAppBundle:Benchmark:q5 }

btw_benchmark_q6:
    pattern: /benchmark/q6/{year}
    defaults: { _controller: BtwAppBundle:Benchmark:q6 }

