parameters:
     btw_election_provider.class: Btw\Bundle\BtwAppBundle\Services\ElectionProvider

services:
     btw_election_provider:
      class: "%btw_election_provider.class%"
      arguments:
              entityManager: "@doctrine.orm.entity_manager"