parameters:
#    btw_app.example.class: Btw\Bundle\BtwAppBundle\Example
     btw_election_provider.class: Btw\Bundle\BtwAppBundle\Services\DummyElectionProvider

services:
#    btw_app.example:
#        class: %btw_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

     btw_election_provider:
      class: "%btw_election_provider.class%"